services:
  frontend:
        build:
          context: ./frontend/
          dockerfile: Dockerfile
          target: dev

        ports:
          - 5173:5173 #<host_port>:<container_port/protocol_port>

        env_file:
          - path: ./frontend/.env  # to export env to the container

        volumes:
          - ./frontend:/frontend/dev #mounted volume hide containers node_module
          - /frontend/dev/node_modules # need this to prevent override

        environment:
          - CHOKIDAR_USEPOLLING=true # Helps Vite detect file changes in Docker   

        depends_on:
         - server

      
  
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
      target : dev

    ports:
     - 3000:3000

    env_file:
      - path: ./server/.env

    volumes:
      - ./server:/server/dev
      - /server/dev/node_modules

    depends_on: 
     - mongo
      
    

  mongo:
    image: mongo
    volumes:
      - cv:/data/db


volumes:
  cv:




